### ISSUE TITLE
Preview types error in create-react-app

### ISSUE THREAD

**Issue by MejanH** [wyozi/react-pptx#631]
- reproducible on both `react-script` v4 and v5.
- error: `Could not find a declaration file for module 'react-pptx/preview'. '**/node_modules/.pnpm/react-pptx@2.16.0_react@18.2.0/node_modules/react-pptx/preview/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-pptx` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-pptx/preview';`ts(7016)`

**temporary fix**:
```typescript
// ./types/react-pptx/index.d.ts
declare module 'react-pptx/preview' {
    import Preview from 'react-pptx/dist/preview/Preview';
    export default Preview;
}
```
```json
// tsconfig.json
    "typeRoots": [
      "./types",
      "./node_modules/@types"
    ],
```
- I also tried with [rollup-copy-plugin](https://www.npmjs.com/package/rollup-plugin-copy) to copy the preview `d.ts` file into the preview file. even though it worked didn't find a simple way to delete the existing `Preview.d.ts` file after copy.

I would make PR if my changes weren't that complicated. also, I am new to npm package contribution. I would appreciate your support. Thanks

**Comment by wyozi** [comment]
Thanks for the issue. This was an interesting problem to look at 😁  The latest version 2.6.1 should fix this.

Your comment about rollup-plugin-copy was one of the keys to figuring it out, but I ended up having some issues with the relative import paths (since `dist/preview/Preview` importing `dist/index.ts` looks different than `preview/index` importing `dist/index.ts`). In the end the easiest solution seemed to be creating a virtual file that imports the preview, placing that to `preview/index.js` and creating a stub type file for the preview that just re-exports the Preview types. This is probably the cleanest solution I can think of at the moment

**Comment by MejanH** [comment]
Thanks for the fix. I also couldn't decide what should have been the cleanest solution. or I would make PR like my previews two PR. So, had to create the issue. Thanks for your support. 👌
